# Generated by Django 5.1.3 on 2024-12-04 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='images', verbose_name='Profile Image')),
                ('commenter_name', models.CharField(max_length=100, verbose_name='Commenter Name')),
                ('comment_text', models.TextField(blank=True, null=True, verbose_name='Comment Text')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name_en', models.CharField(max_length=200, verbose_name='Department Name (EN)')),
                ('department_name_ru', models.CharField(max_length=200, verbose_name='Department Name (RU)')),
                ('department_name_kk', models.CharField(max_length=200, verbose_name='Department Name (KK)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Department Description (EN)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Department Description (RU)')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Department Description (KK)')),
                ('banner_image', models.ImageField(upload_to='department_images/', verbose_name='Department Banner Image')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='images', verbose_name='Profile Image')),
                ('full_name_en', models.CharField(max_length=50, verbose_name='Full Name (EN)')),
                ('full_name_ru', models.CharField(max_length=50, verbose_name='Full Name (RU)')),
                ('full_name_kk', models.CharField(max_length=50, verbose_name='Full Name (KK)')),
                ('job_title_en', models.CharField(max_length=50, verbose_name='Position (EN)')),
                ('job_title_ru', models.CharField(max_length=50, verbose_name='Position (RU)')),
                ('job_title_kk', models.CharField(max_length=50, verbose_name='Position (KK)')),
                ('contact_number', models.CharField(max_length=13, verbose_name='Phone Number')),
                ('email_address', models.EmailField(max_length=200, verbose_name='Email Address')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='images', verbose_name='Image File')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline_en', models.CharField(max_length=100, verbose_name='Headline Text (EN)')),
                ('headline_ru', models.CharField(max_length=100, verbose_name='Headline Text (RU)')),
                ('headline_kk', models.CharField(max_length=100, verbose_name='Headline Text (KK)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (EN)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description (RU)')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Description (KK)')),
            ],
            options={
                'verbose_name': 'Landing Page',
                'verbose_name_plural': 'Landing Pages',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100, verbose_name='Sender Full Name')),
                ('contact_number', models.CharField(max_length=100, verbose_name='Contact Number')),
                ('message_content', models.TextField(blank=True, null=True, verbose_name='Message Content')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Service Image')),
                ('service_name_en', models.CharField(max_length=200, verbose_name='Service Name (EN)')),
                ('service_name_ru', models.CharField(max_length=200, verbose_name='Service Name (RU)')),
                ('service_name_kk', models.CharField(max_length=200, verbose_name='Service Name (KK)')),
                ('service_description_en', models.TextField(blank=True, null=True, verbose_name='Service Description (EN)')),
                ('service_description_ru', models.TextField(blank=True, null=True, verbose_name='Service Description (RU)')),
                ('service_description_kk', models.TextField(blank=True, null=True, verbose_name='Service Description (KK)')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Slug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Slug Title (EN)')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Slug Title (RU)')),
                ('title_kk', models.CharField(max_length=200, verbose_name='Slug Title (KK)')),
                ('content_en', models.TextField(verbose_name='Slug Content (EN)')),
                ('content_ru', models.TextField(verbose_name='Slug Content (RU)')),
                ('content_kk', models.TextField(verbose_name='Slug Content (KK)')),
            ],
            options={
                'verbose_name': 'Slug',
                'verbose_name_plural': 'Slugs',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Social Network Name')),
                ('link', models.URLField(verbose_name='Profile URL')),
            ],
            options={
                'verbose_name': 'Social Network',
                'verbose_name_plural': 'Social Networks',
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline_en', models.CharField(max_length=100, verbose_name='Headline Text (EN)')),
                ('headline_ru', models.CharField(max_length=100, verbose_name='Headline Text (RU)')),
                ('headline_kk', models.CharField(max_length=100, verbose_name='Headline Text (KK)')),
                ('image', models.ImageField(upload_to='images', verbose_name='Image')),
                ('name_en', models.CharField(max_length=50, verbose_name='Name (EN)')),
                ('name_ru', models.CharField(max_length=50, verbose_name='Name (RU)')),
                ('name_kk', models.CharField(max_length=50, verbose_name='Name (KK)')),
                ('address_en', models.CharField(max_length=200, verbose_name='Location (EN)')),
                ('address_ru', models.CharField(max_length=200, verbose_name='Location (RU)')),
                ('address_kk', models.CharField(max_length=200, verbose_name='Location (KK)')),
                ('contact_number', models.CharField(max_length=14, verbose_name='Phone Number')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos', verbose_name='Video File')),
                ('social_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.social', verbose_name='Social Media')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
