# Generated by Django 4.2.5 on 2024-11-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aboutus_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='social_media',
        ),
        migrations.AddField(
            model_name='doctors',
            name='email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='phone',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
