# Generated by Django 4.2.5 on 2024-11-23 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_doctors_social_media_doctors_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='social_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.social'),
        ),
    ]
