"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _  

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LANGUAGE_CODE = 'en'  
LANGUAGES = [
    ('en', _('English')),
    ('ru', _('Russian')),
    ('kk', _('Kazakh')),
]
LOCALE_PATHS = [
    BASE_DIR / 'locale',  # Directory where .po files will be stored
]
LANGUAGE_COOKIE_NAME = 'django_language'


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@zu-_22d&0^d)0c82!5!sy!#w9a0chlg8)ai@u%)k)tx3x7xya'

DEBUG = True

ALLOWED_HOSTS = [
    "alamis.kz",
    "amaarclinic.pythonanywhere.com",
    "localhost",
    "127.0.0.1"
]
CSRF_TRUSTED_ORIGINS = [
    'https://alamis.kz',
    "http://localhost",
    "http://127.0.0.1"
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app'
]

MIDDLEWARE = [
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app.middleware.SetLanguageMiddleware',
     
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

TIME_ZONE = 'UTC'
USE_TZ = True
USE_I18N =True
USE_L10N = True
JAZZMIN_SETTINGS = {
    "site_title": "Alamis",
    "site_header": "Alamis",
    "site_brand": "Alamis",
    "site_logo": "images/alamis-logo.png",  # Path to your logo
    "site_logo_classes": "img-circle",
    "welcome_sign": "Welcome to the Alamis Clinic superadmin panel",
    "copyright": "Acme Alamis Ltd",
    "search_model": ["app.Doctor", "app.Department", "app.Message"],
    "user_avatar": None,
    "navbar": "navbar-navy navbar-dark",
    "show_sidebar": True,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        # Model-specific icons
        "app.Social": "fas fa-share-alt",  # Social links
        "app.Slug": "fas fa-link",  # Slug links
        "app.Doctor": "fas fa-user-md",  # Doctor profile
        "app.Landing": "fas fa-home",  # Landing page
        "app.AboutUs": "fas fa-info-circle",  # About Us section
        "app.Message": "fas fa-envelope",  # Messages
        "app.Comment": "fas fa-comment-alt",  # Comments
        "app.Department": "fas fa-hospital",  # Departments
        "app.Gallery": "fas fa-images",  # Gallery images
        "app.Service": "fas fa-hand-holding-medical",  # Services offered
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "app.Social": "collapsible",
        "app.Department": "vertical_tabs",
    },
}


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-navy",
    "accent": "accent-primary",
    "navbar": "navbar-navy navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": True,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-navy",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "footer": "sidebar-dark-navy",
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
        "language_chooser": True,
    }
}



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
